test notifications

diff --git a/.github/workflows/HelloWorld.yml b/.github/workflows/HelloWorld.yml
--- a/.github/workflows/HelloWorld.yml
+++ b/.github/workflows/HelloWorld.yml
@@ -1,36 +1,22 @@
-# This is a basic workflow to help you get started with Actions
+name: buildfail
 
-name: buildbreak
-
-# Controls when the workflow will run
 on:
-  
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-  
-  #schedule:
-  #  - cron: "*/2 * * * *"
+  workflow_dispatch:
 
-  # Allows you to run this workflow manually from the Actions tab
-  
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
-    runs-on: ubuntulates
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
+    runs-on: ubuntu-latest
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
+      - name: Run script
         run: echo Hello World!!
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Intentional failure
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          echo "Failing build"
+          exit 1
+
+      - name: Send notification on failure
+        if: failure()
+        run: echo "This step runs because the build failed"
